index:
  path: /{_locale}/
  controller: App\Controller\HomeController::index

easy_admin_bundle:
  resource: '@EasyAdminBundle/Controller/EasyAdminController.php'
  prefix: /fr/admin
  type: annotation